index:
    path: /
    controller: App\Controller\PostController::index
    methods: GET

add_post:
    path: /post/publish
    controller: App\Controller\PostController::publishPost
    methods: POST

list_posts:
    path: /post/list
    controller: App\Controller\PostController::listPosts
    methods: GET

show_post:
    path: /post/{postId}
    controller: App\Controller\PostController::viewPost
    methods: GET
