index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

signup:
    path: /signup
    controller: App\Controller\UserController::register

login:
    path: /signin
    controller: App\Controller\SecurityController::login

home:
    path: /home
    methods: GET
    controller: App\Controller\PostController::listPosts

add_post:
    path: /post/publish
    controller: App\Controller\PostController::publishPost
    methods: POST

list_posts:
    path: /post/list
    controller: App\Controller\PostController::listPosts
    methods: GET

show_post:
    path: /post/{postId}
    controller: App\Controller\PostController::viewPost
    methods: GET
